---
- name: Setup DotNet
  hosts: pi
  remote_user: adamgrofe

  tasks:

  - name: Install dotnet dependencies
    become: true
    ansible.builtin.apt:
      name: 
        - libc6
        - libgcc1
        - libgssapi-krb5-2 
          #        - libicu70
        - libicu72
        - libssl3
        - libstdc++6
        - zlib1g
      state: present

  - name: Download installer and run
    ansible.builtin.shell: |
      mkdir ~/dotnet-install
      cd ~/dotnet-install
      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --channel 8.0

  - name: Add dotnet to path
    ansible.builtin.lineinfile:
      path: ~/.bashrc
      state: present
      line: "PATH=$PATH:~/.dotnet"
